### PR TITLE
enable set command on console

### PR DESCRIPTION
**Pull request by scorninpc**
enabling this command on console, we can automatic set tags, for new vips, or when a quest is done, for example

### CODE REVIEW

**Comment by Refrac** [comment]
Also you have two Player player variables this is causing a compiler error

**Comment by scorninpc** [comment]
I confess that i don't opened `locale.sendCustomMessage` to see how it's work, and just do the easiest way. Sorry! 

Don't merge, tomorrow i'll do the correct way!

**Comment by scorninpc** [comment]
Ok, i cannot wait for tomorrow hahaha

Take a look now

image

**Review by Refrac — APPROVED** [review]

**Comment by Refrac** [comment]
LGTM!

**Pull request merged**
